language: node_js
dist: xenial
node_js:
  - "10"
before_script:
  - sudo apt-get install -y wkhtmltopdf
script:
  - yarn run publish
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./build
  target-branch: gh-pages
  on:
    branch: master
addons:
  apt:
    update: true
