language: node_js
dist: xenial
node_js:
  - "10"
before_script:
  - wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
  - sudo dpkg -i wkhtmltox_0.12.5-1.xenial_amd64.deb
script:
  - yarn run publish
deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./build
  target-branch: gh-pages
  on:
    branch: master
